### ISSUE TITLE
Allow disabling Mathquill for selected expressions

### ISSUE THREAD

**Issue by wompking** [DesModder/DesModder#275] opened 2021-11-22 18:13 UTC
This should give certain graphs a performance boost so dynamic simulation data doesn't need to be rechecked / rerendered

**Comment by jared-hughes** [comment] 2021-11-23 04:17
Duplicate of https://github.com/DesModder/DesModder/issues/197. Note that this will not increase the performance of simulations over putting the list in a folder and closing the folder. The list still needs to get re-latexified and re-parsed.

**Closed by jared-hughes** 2021-11-23 04:17 UTC
Labels: duplicate
